// Builds a compact text catalog of every Nova node, grouped by category and
// formatted as a Geo.* signature → output type. Used by the AI assistant's
// system prompt during build-intent turns so the model knows what tools it
// has and writes graph-native code (single Geo.* calls that map to single
// visual nodes) instead of re-implementing built-in nodes inside Python
// blocks.
//
// Each line of the catalog has the shape:
//   Geo.createBox(center, width, depth, height) → Mesh3
//
// We derive the signature from node.codegen.python (the same template Nova
// uses when transpiling node graphs to Python), so the catalog is always
// consistent with the parser. If a node lacks codegen.python it is omitted
// — that node can't be generated by code-write-back anyway.

import { coreNodes } from '../nodes/coreNodes.js';

const TYPE_ALIASES = {
  mesh: 'Mesh3',
  point: 'Point3',
  vector: 'Vector3',
  line: 'Line3',
  curve: 'Curve3',
  polyline: 'Polyline3',
  circle: 'Circle3',
  plane: 'Plane3',
  number: 'number',
  integer: 'int',
  string: 'string',
  boolean: 'bool',
  list: 'list',
  any: 'any'
};

function readableType(t) {
  if (!t) return 'any';
  return TYPE_ALIASES[t] || t;
}

// Normalize codegen.python like
//   '{{solid}} = Geo.createBox({{center}}, {{width}}, {{depth}}, {{height}})'
// to its callable shape:
//   'Geo.createBox(center, width, depth, height)'
function extractCallExpression(template) {
  if (typeof template !== 'string') return null;
  // Only keep single-line codegens — multi-line templates are
  // construction scripts (e.g. ellipse-from-for-loop) and we'd rather
  // skip them entirely than pollute the catalog with confusing snippets.
  if (template.indexOf('\n') !== -1) return null;
  // Drop the `{{output}} = ` prefix if present (but not `==` comparisons).
  const eqIdx = template.indexOf('=');
  let body = eqIdx > -1 && template.indexOf('==') === -1 ? template.slice(eqIdx + 1).trim() : template.trim();
  // Strip {{name}} → name throughout.
  body = body.replace(/\{\{([^}]+)\}\}/g, '$1');
  // Remove trailing semicolons / comments.
  body = body.replace(/;\s*$/, '').replace(/\s*#.*$/, '').trim();
  if (!body) return null;
  // The catalog is about callable Geo.* shapes the user can write in a
  // single Python assignment. Skip control-flow keywords, list comps,
  // method chains on instance variables, etc. — those don't map to a
  // simple "one node = one Geo.X(...) call" mental model.
  if (body.startsWith('[') || body.startsWith('for ') || body.startsWith('if ')) return null;
  if (!body.includes('(')) return null;
  return body;
}

function nodeSignature(node) {
  const expr = extractCallExpression(node.codegen && node.codegen.python);
  if (!expr) return null;
  const outputs = Array.isArray(node.outputs) ? node.outputs : [];
  const outType = outputs.length > 0 ? readableType(outputs[0].type) : null;
  return outType ? `${expr} → ${outType}` : expr;
}

// Maps each node-backed Geo.* method name to its auto-derived signature line
// (e.g. createBox → "Geo.createBox(center, width, depth, height) → Mesh3").
// The capability ledger uses this so design-facing signatures stay derived from
// the registry (drift-proof) rather than hand-copied. First node wins on dupes.
export function getGeoSignatureMap() {
  const map = {};
  for (const node of coreNodes) {
    const expr = extractCallExpression(node.codegen && node.codegen.python);
    if (!expr) continue;
    const m = expr.match(/^Geo\.([A-Za-z_][A-Za-z0-9_]*)\s*\(/);
    if (!m || map[m[1]]) continue;
    const outputs = Array.isArray(node.outputs) ? node.outputs : [];
    const outType = outputs.length > 0 ? readableType(outputs[0].type) : null;
    map[m[1]] = outType ? `${expr} → ${outType}` : expr;
  }
  return map;
}

// Returns a string the system prompt can paste verbatim. Cached because
// it's deterministic from the node registry; recompute on rebuild.
let cachedCatalog = null;

export function buildNodeCatalog() {
  if (cachedCatalog) return cachedCatalog;

  const byCategory = new Map();
  for (const node of coreNodes) {
    const sig = nodeSignature(node);
    if (!sig) continue;
    const cat = node.category || 'other';
    if (!byCategory.has(cat)) byCategory.set(cat, []);
    byCategory.get(cat).push({ name: node.name || node.type, sig, description: node.description || '' });
  }

  // Stable category order — common-intent categories first.
  const order = [
    'solids', 'surfaces', 'curves', 'patterns',
    'point', 'vector', 'plane',
    'math', 'logic', 'list',
    'input', 'output', 'custom', 'testing', 'geometry'
  ];
  const categoryNames = {
    solids: 'Solids (Mesh3 producers + boolean ops)',
    surfaces: 'Surfaces',
    curves: 'Curves',
    patterns: 'Patterns (point/curve/mesh generators — prefer these over manual for-loops)',
    point: 'Point construction',
    vector: 'Vector construction & math',
    plane: 'Planes',
    math: 'Math',
    logic: 'Logic',
    list: 'List operations',
    input: 'Inputs',
    output: 'Outputs (Watch, Display, etc.)',
    custom: 'Custom (Python fallback lives here — use ONLY when nothing else fits)',
    testing: 'Testing utilities',
    geometry: 'Generic geometry helpers'
  };

  const lines = ['=== NOVA NODE INVENTORY ===', 'Each entry below is a single visual node. Write one of these Geo.* calls per Python assignment and Nova will materialize it as a node automatically.', ''];
  for (const cat of order) {
    const nodes = byCategory.get(cat);
    if (!nodes || nodes.length === 0) continue;
    lines.push(`## ${categoryNames[cat] || cat}`);
    // Dedupe — some nodes share a codegen.python (aliases, by-X-by-Y variants).
    const seen = new Set();
    for (const node of nodes) {
      if (seen.has(node.sig)) continue;
      seen.add(node.sig);
      lines.push(node.sig);
    }
    lines.push('');
  }

  // Trailing rules — short, imperative.
  lines.push('## COMPOSITION RULES');
  lines.push('1. For every line of code you write, ask: "Is there a single Geo.* call above that does this?" If yes, USE IT.');
  lines.push('2. If you find yourself writing a for-loop to generate points/curves, look in Patterns first (Geo.phyllotaxis, Geo.hexGrid, Geo.voronoiMesh, Geo.bezier, etc.) — there is almost always a single-call replacement.');
  lines.push('3. Each Python assignment becomes one visual node. Decompose: `box = Geo.createBox(c, w, d, h)` is good; nesting calls is bad (`Geo.createBox(Geo.Point3(0,0,0), 1, 1, 1)` → one ugly node).');
  lines.push('4. Custom.Python is a LAST RESORT. If you must use it, add a comment `# fallback: <one-line reason>` on the first line so the user can see why no single node sufficed.');
  lines.push('5. End every code block with `print(<final_result>)` so the graph has a Watch node and renders something.');

  cachedCatalog = lines.join('\n');
  return cachedCatalog;
}

// Test seam — clear cache between catalogue-mutation tests.
export function _clearCatalogCacheForTests() {
  cachedCatalog = null;
}
