// ============================================
// NODEFLOW AI — NODE REGISTRY (Single Source of Truth)
// ALL categories and node definitions live here.
// No other file should touch NODE_LIBRARY.categories.
// Categories: A→Z. Nodes within each: A→Z.
// ============================================

export const NODE_LIBRARY = { categories: [] };
export const NODE_TYPE_MAP = {};
export const TYPE_COLORS = {
  number: '#a6e3a1', string: '#f9e2af', boolean: '#f38ba8',
  point: '#89b4fa', vector: '#94e2d5', line: '#89b4fa',
  circle: '#89b4fa', list: '#fab387', any: '#a6adc8', function: '#f5c2e7',
  mesh: '#f38ba8', curve: '#94e2d5', plane: '#89b4fa',
  solid: '#f38ba8', surface: '#94e2d5', nurbscurve: '#f9e2af',
  nurbssurface: '#94e2d5', field: '#74c7ec', pattern: '#a6e3a1', revit: '#89dceb',
  revitelement: '#89dceb'
};

// ═══════════════════════════════════════
// 1. CURVES (profiles merged in)
// ═══════════════════════════════════════
NODE_LIBRARY.categories.push({ id: 'curves', name: 'Curves', color: '#94e2d5', icon: '∿', nodes: [
  { type: 'surf-arc', name: 'Arc', icon: '⌒', inputs: [{ id: 'center', name: 'Center', type: 'point' },{ id: 'radius', name: 'Radius', type: 'number' },{ id: 'startAngle', name: 'Start°', type: 'number' },{ id: 'endAngle', name: 'End°', type: 'number' }], outputs: [{ id: 'arc', name: 'Arc', type: 'curve' }], controls: [], preview: true, codegen: { python: '{{arc}} = Geo.Arc3({{center}}, {{radius}}, math.radians({{startAngle}}), math.radians({{endAngle}}))', csharp: '' } },
  { type: 'op-bezier', name: 'Bezier Curve', icon: '∿', inputs: [{ id: 'points', name: 'Control Pts', type: 'list' }], outputs: [{ id: 'curve', name: 'Curve', type: 'curve' }], controls: [], preview: true, codegen: { python: '{{curve}} = Geo.bezier({{points}})', csharp: '' } },
  { type: 'nurbs-blend', name: 'Blend Curves', icon: '↹', inputs: [{ id: 'curve1', name: 'Curve A', type: 'any' },{ id: 'curve2', name: 'Curve B', type: 'any' },{ id: 't', name: 'Blend (0-1)', type: 'number' }], outputs: [{ id: 'curve', name: 'Curve', type: 'curve' }], controls: [], preview: true, codegen: { python: '{{curve}} = Geo.blendCurves({{curve1}}, {{curve2}}, {{t}})', csharp: '' } },
  { type: 'geo-circle', name: 'Circle', icon: '○', inputs: [{ id: 'center', name: 'Center', type: 'point' },{ id: 'radius', name: 'Radius', type: 'number' }], outputs: [{ id: 'circle', name: 'Circle', type: 'circle' }], controls: [{ id: 'plane', type: 'dropdown', options: ['XY','XZ','YZ'], default: 'XY', label: 'Plane' }], preview: true, codegen: { python: '{{circle}} = Geo.Circle3({{center}}, {{radius}})', csharp: '' } },
  { type: 'prof-circle', name: 'Circle Profile', icon: '○', inputs: [{ id: 'center', name: 'Center', type: 'point' },{ id: 'radius', name: 'Radius', type: 'number' },{ id: 'resolution', name: 'Resolution', type: 'number' }], outputs: [{ id: 'profile', name: 'Profile', type: 'list' }], controls: [], preview: true, codegen: { python: '{{profile}} = [Geo.Point3({{center}}.x + {{radius}} * __cos__(2*3.14159*j/int({{resolution}})), {{center}}.y + {{radius}} * __sin__(2*3.14159*j/int({{resolution}})), {{center}}.z) for j in range(int({{resolution}}))]', csharp: '' } },
  { type: 'prof-ellipse', name: 'Ellipse Profile', icon: '⬭', inputs: [{ id: 'center', name: 'Center', type: 'point' },{ id: 'width', name: 'Width', type: 'number' },{ id: 'depth', name: 'Depth', type: 'number' },{ id: 'rotation', name: 'Rotation°', type: 'number' },{ id: 'resolution', name: 'Resolution', type: 'number' }], outputs: [{ id: 'profile', name: 'Profile', type: 'list' }], controls: [], preview: true, codegen: { python: '_ep=[]\\nfor _j in range(int({{resolution}})):\\n _a=2*3.14159*_j/int({{resolution}});_x={{width}}/2*__cos__(_a);_y={{depth}}/2*__sin__(_a);_r={{rotation}}*3.14159/180\\n _ep.append(Geo.Point3({{center}}.x+_x*__cos__(_r)-_y*__sin__(_r),{{center}}.y+_x*__sin__(_r)+_y*__cos__(_r),{{center}}.z))\\n{{profile}}=_ep', csharp: '' } },
  { type: 'op-interpolate', name: 'Interpolate', icon: '⌇', inputs: [{ id: 'points', name: 'Points', type: 'list' }], outputs: [{ id: 'curve', name: 'Curve', type: 'curve' }], controls: [], preview: true, codegen: { python: '{{curve}} = Geo.interpolate({{points}})', csharp: '' } },
  { type: 'nurbs-interpolate', name: 'Interpolate NURBS', icon: '⌒', inputs: [{ id: 'points', name: 'Through Pts', type: 'list' },{ id: 'degree', name: 'Degree', type: 'number' }], outputs: [{ id: 'curve', name: 'Curve', type: 'curve' }], controls: [], preview: true, codegen: { python: '{{curve}} = Geo.nurbsInterpolate({{points}}, {{degree}})', csharp: '' } },
  { type: 'nurbs-curve', name: 'NURBS Curve', icon: '〰', inputs: [{ id: 'points', name: 'Control Pts', type: 'list' },{ id: 'degree', name: 'Degree', type: 'number' }], outputs: [{ id: 'curve', name: 'Curve', type: 'curve' }], controls: [], preview: true, codegen: { python: '{{curve}} = Geo.createNurbsCurve({{points}}, {{degree}})', csharp: '' } },
  { type: 'surf-polyline', name: 'Polyline', icon: '⏣', inputs: [{ id: 'points', name: 'Points', type: 'list' },{ id: 'closed', name: 'Closed', type: 'boolean' }], outputs: [{ id: 'polyline', name: 'Polyline', type: 'curve' }], controls: [], preview: true, codegen: { python: '{{polyline}} = Geo.Polyline3({{points}}, {{closed}})', csharp: '' } },
  { type: 'prof-rect', name: 'Rectangle Profile', icon: '▭', inputs: [{ id: 'center', name: 'Center', type: 'point' },{ id: 'width', name: 'Width', type: 'number' },{ id: 'depth', name: 'Depth', type: 'number' }], outputs: [{ id: 'profile', name: 'Profile', type: 'list' }], controls: [], preview: true, codegen: { python: '{{profile}} = [Geo.Point3({{center}}.x-{{width}}/2,{{center}}.y-{{depth}}/2,{{center}}.z),Geo.Point3({{center}}.x+{{width}}/2,{{center}}.y-{{depth}}/2,{{center}}.z),Geo.Point3({{center}}.x+{{width}}/2,{{center}}.y+{{depth}}/2,{{center}}.z),Geo.Point3({{center}}.x-{{width}}/2,{{center}}.y+{{depth}}/2,{{center}}.z)]', csharp: '' } },
  { type: 'nurbs-tween', name: 'Tween Curves', icon: '≋', inputs: [{ id: 'curve1', name: 'Curve A', type: 'any' },{ id: 'curve2', name: 'Curve B', type: 'any' },{ id: 'count', name: 'Count', type: 'number' }], outputs: [{ id: 'curves', name: 'Curves', type: 'list' }], controls: [], preview: true, codegen: { python: '{{curves}} = Geo.tweenCurves({{curve1}}, {{curve2}}, {{count}})', csharp: '' } }
] });

// ═══════════════════════════════════════
// 2. CUSTOM / AI
// ═══════════════════════════════════════
NODE_LIBRARY.categories.push({ id: 'custom', name: 'Custom / AI', color: '#94e2d5', icon: '✦', nodes: [
  { type: 'custom-ainode', name: 'AI Generated', icon: '✦', inputs: [{ id: 'in0', name: 'Input', type: 'any' }], outputs: [{ id: 'out0', name: 'Output', type: 'any' }], controls: [{ id: 'prompt', type: 'text', default: 'Describe behavior…', label: 'Prompt' }], preview: true, codegen: { python: '# AI: {{ctrl.prompt}}\\n{{out0}} = {{in0}}', csharp: '' } },
  { type: 'custom-code', name: 'Code Block', icon: '{ }', inputs: [{ id: 'input0', name: 'input0', type: 'any' }], outputs: [{ id: 'output0', name: 'output0', type: 'any' }], controls: [{ id: 'code', type: 'text', default: 'return input0;', label: 'Code' }], preview: true, codegen: { python: '{{output0}} = (lambda input0: {{ctrl.code}})({{input0}})', csharp: '' } },
  { type: 'custom-comment', name: 'Comment', icon: '💬', inputs: [], outputs: [], controls: [{ id: 'text', type: 'text', default: 'Add notes here…', label: 'Note' }], preview: false, codegen: { python: '# {{ctrl.text}}', csharp: '' } },
  { type: 'custom-formula', name: 'Formula', icon: 'ƒ', inputs: [{ id: 'x', name: 'x', type: 'number' },{ id: 'y', name: 'y', type: 'number' }], outputs: [{ id: 'result', name: 'Result', type: 'number' }], controls: [{ id: 'expr', type: 'text', default: 'x + y', label: 'Expression' }], preview: true, codegen: { python: '{{result}} = {{ctrl.expr}}', csharp: '' } },
  { type: 'custom-python', name: 'Python', icon: '🐍', inputs: [{ id: 'input0', name: 'input', type: 'any' }], outputs: [{ id: 'output0', name: 'output', type: 'any' }], controls: [{ id: 'code', type: 'text', default: 'output = input', label: 'Python' }], preview: true, codegen: { python: '# Python block\\n{{ctrl.code}}', csharp: '' } }
] });

// ═══════════════════════════════════════
// 3. INPUT
// ═══════════════════════════════════════
NODE_LIBRARY.categories.push({ id: 'input', name: 'Input', color: '#cba6f7', icon: '⊙', nodes: [
  { type: 'boolean-input', name: 'Boolean', icon: '◑', inputs: [], outputs: [{ id: 'value', name: 'Value', type: 'boolean' }], controls: [{ id: 'val', type: 'dropdown', options: ['True','False'], default: 'True', label: 'Value' }], preview: true, codegen: { python: '{{value}} = {{ctrl.val}}', csharp: 'bool {{value}} = {{ctrl.val_lower}};' } },
  { type: 'integer-input', name: 'Integer', icon: 'Z', inputs: [], outputs: [{ id: 'value', name: 'Value', type: 'number' }], controls: [{ id: 'val', type: 'number', default: 1, label: 'Value' }], preview: true, codegen: { python: '{{value}} = int({{ctrl.val}})', csharp: 'int {{value}} = {{ctrl.val}};' } },
  { type: 'number-input', name: 'Number', icon: '#', inputs: [], outputs: [{ id: 'value', name: 'Value', type: 'number' }], controls: [{ id: 'val', type: 'number', default: 0, label: 'Value' }], preview: true, codegen: { python: '{{value}} = {{ctrl.val}}', csharp: 'double {{value}} = {{ctrl.val}};' } },
  { type: 'slider-input', name: 'Slider', icon: '⊶', inputs: [], outputs: [{ id: 'value', name: 'Value', type: 'number' }], controls: [{ id: 'min', type: 'number', default: 0, label: 'Min' },{ id: 'max', type: 'number', default: 100, label: 'Max' },{ id: 'val', type: 'range', default: 50, label: 'Value' }], preview: true, codegen: { python: '{{value}} = {{ctrl.val}}', csharp: 'double {{value}} = {{ctrl.val}};' } },
  { type: 'text-input', name: 'Text', icon: 'T', inputs: [], outputs: [{ id: 'value', name: 'Value', type: 'string' }], controls: [{ id: 'val', type: 'text', default: 'Hello', label: 'Text' }], preview: true, codegen: { python: '{{value}} = "{{ctrl.val}}"', csharp: 'string {{value}} = "{{ctrl.val}}";' } }
] });

// ═══════════════════════════════════════
// 4. LINE
// ═══════════════════════════════════════
NODE_LIBRARY.categories.push({ id: 'line', name: 'Line', color: '#a6e3a1', icon: '╱', nodes: [
  { type: 'line-bypointanddirection', name: 'Line.ByPointAndDirection', icon: '→', inputs: [{ id: 'origin', name: 'Origin', type: 'point' },{ id: 'direction', name: 'Direction', type: 'vector' },{ id: 'length', name: 'Length', type: 'number' }], outputs: [{ id: 'line', name: 'Line', type: 'line' }], controls: [{ id: 'length', type: 'formula', default: '10', label: 'Length' }], preview: true, codegen: { python: '{{line}} = Geo.Line3({{origin}}, {{origin}}.add({{direction}}.normalize().scale({{length}})))', csharp: '' } },
  { type: 'line-bystartpointendpoint', name: 'Line.ByStartPointEndPoint', icon: '╱', inputs: [{ id: 'startPoint', name: 'Start Point', type: 'point' },{ id: 'endPoint', name: 'End Point', type: 'point' }], outputs: [{ id: 'line', name: 'Line', type: 'line' }], controls: [], preview: true, codegen: { python: '{{line}} = Geo.Line3({{startPoint}}, {{endPoint}})', csharp: '' } },
  { type: 'line-deconstruct', name: 'Line.Deconstruct', icon: '⊙', inputs: [{ id: 'curve', name: 'Curve', type: 'any' }], outputs: [{ id: 'start', name: 'Start', type: 'point' },{ id: 'end', name: 'End', type: 'point' },{ id: 'length', name: 'Length', type: 'number' },{ id: 'midpoint', name: 'MidPoint', type: 'point' },{ id: 'direction', name: 'Direction', type: 'vector' }], controls: [], preview: true, codegen: { python: '{{start}} = {{curve}}.start\\n{{end}} = {{curve}}.end\\n{{length}} = {{curve}}.length()\\n{{midpoint}} = {{start}}.lerp({{end}}, 0.5)\\n{{direction}} = {{curve}}.direction()', csharp: '' } },
  { type: 'line-direction', name: 'Line.Direction', icon: '→', inputs: [{ id: 'curve', name: 'Curve', type: 'any' }], outputs: [{ id: 'direction', name: 'Direction', type: 'vector' }], controls: [], preview: true, codegen: { python: '{{direction}} = {{curve}}.direction()', csharp: '' } },
  { type: 'line-endpoint', name: 'Line.EndPoint', icon: '⊙', inputs: [{ id: 'curve', name: 'Curve', type: 'any' }], outputs: [{ id: 'point', name: 'Point', type: 'point' }], controls: [], preview: true, codegen: { python: '{{point}} = {{curve}}.end', csharp: '' } },
  { type: 'line-length', name: 'Line.Length', icon: '⟷', inputs: [{ id: 'curve', name: 'Curve', type: 'any' }], outputs: [{ id: 'length', name: 'Length', type: 'number' }], controls: [], preview: true, codegen: { python: '{{length}} = {{curve}}.length()', csharp: '' } },
  { type: 'line-startpoint', name: 'Line.StartPoint', icon: '⊙', inputs: [{ id: 'curve', name: 'Curve', type: 'any' }], outputs: [{ id: 'point', name: 'Point', type: 'point' }], controls: [], preview: true, codegen: { python: '{{point}} = {{curve}}.start', csharp: '' } }
] });

// ═══════════════════════════════════════
// 5. LIST (33 nodes, A→Z)
// ═══════════════════════════════════════
NODE_LIBRARY.categories.push({ id: 'list', name: 'List', color: '#fab387', icon: '☰', nodes: [
  { type: 'list-average', name: 'List.Average', icon: 'μ', inputs: [{ id: 'list', name: 'List', type: 'list' }], outputs: [{ id: 'result', name: 'Result', type: 'number' }], controls: [], preview: true, codegen: { python: '{{result}} = sum({{list}}) / len({{list}})', csharp: '' } },
  { type: 'list-chunk', name: 'List.Chunk', icon: '▤', inputs: [{ id: 'list', name: 'List', type: 'list' },{ id: 'size', name: 'Size', type: 'number' }], outputs: [{ id: 'result', name: 'Result', type: 'list' }], controls: [{ id: 'size', type: 'formula', default: '3', label: 'Size' }], preview: true, codegen: { python: '{{result}} = [{{list}}[i:i+int({{size}})] for i in range(0, len({{list}}), int({{size}}))]', csharp: '' } },
  { type: 'list-contains', name: 'List.Contains', icon: '∈', inputs: [{ id: 'list', name: 'List', type: 'list' },{ id: 'item', name: 'Item', type: 'any' }], outputs: [{ id: 'result', name: 'Result', type: 'boolean' }], controls: [{ id: 'item', type: 'formula', default: '0', label: 'Item' }], preview: true, codegen: { python: '{{result}} = {{item}} in {{list}}', csharp: '' } },
  { type: 'list-count', name: 'List.Count', icon: '#', inputs: [{ id: 'list', name: 'List', type: 'list' }], outputs: [{ id: 'count', name: 'Count', type: 'number' }], controls: [], preview: true, codegen: { python: '{{count}} = len({{list}})', csharp: '' } },
  { type: 'list-create', name: 'List.Create', icon: '[ ]', inputs: [{ id: 'item0', name: 'Item 0', type: 'any' },{ id: 'item1', name: 'Item 1', type: 'any' }], outputs: [{ id: 'list', name: 'List', type: 'list' }], controls: [], preview: true, dynamicInputs: true, codegen: { python: '{{list}} = []', csharp: '' } },
  { type: 'list-cross-ref', name: 'List.CrossReference', icon: '✚', inputs: [{ id: 'listA', name: 'List A', type: 'list' },{ id: 'listB', name: 'List B', type: 'list' }], outputs: [{ id: 'pairsA', name: 'A Values', type: 'list' },{ id: 'pairsB', name: 'B Values', type: 'list' }], controls: [], preview: true, codegen: { python: '{{pairsA}} = [a for a in {{listA}} for b in {{listB}}]\\n{{pairsB}} = [b for a in {{listA}} for b in {{listB}}]', csharp: '' } },
  { type: 'list-filterbool', name: 'List.FilterByBoolean', icon: '⊘', inputs: [{ id: 'list', name: 'List', type: 'list' },{ id: 'mask', name: 'Booleans', type: 'list' }], outputs: [{ id: 'inList', name: 'In (True)', type: 'list' },{ id: 'outList', name: 'Out (False)', type: 'list' }], controls: [], preview: true, codegen: { python: '{{inList}} = [v for v,m in zip({{list}},{{mask}}) if m]\\n{{outList}} = [v for v,m in zip({{list}},{{mask}}) if not m]', csharp: '' } },
  { type: 'list-first', name: 'List.First', icon: '⊢', inputs: [{ id: 'list', name: 'List', type: 'list' }], outputs: [{ id: 'item', name: 'Item', type: 'any' }], controls: [], preview: true, codegen: { python: '{{item}} = {{list}}[0]', csharp: '' } },
  { type: 'list-flatten', name: 'List.Flatten', icon: '▤', inputs: [{ id: 'list', name: 'List', type: 'list' }], outputs: [{ id: 'result', name: 'Result', type: 'list' }], controls: [], preview: true, codegen: { python: '{{result}} = [item for sub in {{list}} for item in (sub if isinstance(sub, list) else [sub])]', csharp: '' } },
  { type: 'list-get', name: 'List.GetItem', icon: '[i]', inputs: [{ id: 'list', name: 'List', type: 'list' },{ id: 'index', name: 'Index', type: 'number' }], outputs: [{ id: 'item', name: 'Item', type: 'any' }], controls: [{ id: 'index', type: 'formula', default: '0', label: 'Index' }], preview: true, codegen: { python: '{{item}} = {{list}}[int({{index}})]', csharp: '' } },
  { type: 'list-groupby', name: 'List.GroupBy', icon: '⊞', inputs: [{ id: 'list', name: 'List', type: 'list' },{ id: 'keys', name: 'Keys', type: 'list' }], outputs: [{ id: 'groups', name: 'Groups', type: 'list' },{ id: 'groupKeys', name: 'Keys', type: 'list' }], controls: [{ id: 'expr', type: 'formula', default: 'x%3', label: 'Key f(x)' }], preview: true, codegen: { python: '_gd={}\\nfor x in {{list}}:\\n _k={{expr}}\\n if _k not in _gd:_gd[_k]=[]\\n _gd[_k].append(x)\\n{{groupKeys}}=list(_gd.keys())\\n{{groups}}=list(_gd.values())', csharp: '' } },
  { type: 'list-indexof', name: 'List.IndexOf', icon: '#i', inputs: [{ id: 'list', name: 'List', type: 'list' },{ id: 'item', name: 'Item', type: 'any' }], outputs: [{ id: 'index', name: 'Index', type: 'number' }], controls: [{ id: 'item', type: 'formula', default: '0', label: 'Item' }], preview: true, codegen: { python: '{{index}} = {{list}}.index({{item}}) if {{item}} in {{list}} else -1', csharp: '' } },
  { type: 'list-insert', name: 'List.Insert', icon: '+i', inputs: [{ id: 'list', name: 'List', type: 'list' },{ id: 'item', name: 'Item', type: 'any' },{ id: 'index', name: 'Index', type: 'number' }], outputs: [{ id: 'result', name: 'Result', type: 'list' }], controls: [{ id: 'index', type: 'formula', default: '0', label: 'Index' }], preview: true, codegen: { python: '{{result}} = list({{list}})\\n{{result}}.insert(int({{index}}), {{item}})', csharp: '' } },
  { type: 'list-join', name: 'List.Join', icon: '⊕', inputs: [{ id: 'listA', name: 'List A', type: 'list' },{ id: 'listB', name: 'List B', type: 'list' }], outputs: [{ id: 'result', name: 'Result', type: 'list' }], controls: [], preview: true, codegen: { python: '{{result}} = {{listA}} + {{listB}}', csharp: '' } },
  { type: 'list-last', name: 'List.Last', icon: '⊣', inputs: [{ id: 'list', name: 'List', type: 'list' }], outputs: [{ id: 'item', name: 'Item', type: 'any' }], controls: [], preview: true, codegen: { python: '{{item}} = {{list}}[-1]', csharp: '' } },
  { type: 'list-map', name: 'List.Map', icon: 'λ', inputs: [{ id: 'list', name: 'List', type: 'list' }], outputs: [{ id: 'result', name: 'Result', type: 'list' }], controls: [{ id: 'code', type: 'formula', default: 'x * 2', label: 'f(x)' }], preview: true, codegen: { python: '{{result}} = [{{code}} for x in {{list}}]', csharp: '' } },
  { type: 'list-maxval', name: 'List.Max', icon: '↑', inputs: [{ id: 'list', name: 'List', type: 'list' }], outputs: [{ id: 'result', name: 'Result', type: 'number' }], controls: [], preview: true, codegen: { python: '{{result}} = max({{list}})', csharp: '' } },
  { type: 'list-minval', name: 'List.Min', icon: '↓', inputs: [{ id: 'list', name: 'List', type: 'list' }], outputs: [{ id: 'result', name: 'Result', type: 'number' }], controls: [], preview: true, codegen: { python: '{{result}} = min({{list}})', csharp: '' } },
  { type: 'list-pairs', name: 'List.Pairs', icon: '⟷', inputs: [{ id: 'list', name: 'List', type: 'list' }], outputs: [{ id: 'result', name: 'Result', type: 'list' }], controls: [], preview: true, codegen: { python: '{{result}} = list(zip({{list}}[:-1], {{list}}[1:]))', csharp: '' } },
  { type: 'list-range', name: 'List.Range', icon: '…', inputs: [{ id: 'start', name: 'Start', type: 'number' },{ id: 'end', name: 'End', type: 'number' },{ id: 'step', name: 'Step', type: 'number' }], outputs: [{ id: 'list', name: 'List', type: 'list' }], controls: [{ id: 'start', type: 'formula', default: '0', label: 'Start' },{ id: 'end', type: 'formula', default: '10', label: 'End' },{ id: 'step', type: 'formula', default: '1', label: 'Step' }], preview: true, codegen: { python: '{{list}} = list(range(int({{start}}), int({{end}}), int({{step}})))', csharp: '' } },
  { type: 'list-remove', name: 'List.Remove', icon: '-i', inputs: [{ id: 'list', name: 'List', type: 'list' },{ id: 'index', name: 'Index', type: 'number' }], outputs: [{ id: 'result', name: 'Result', type: 'list' },{ id: 'removed', name: 'Removed', type: 'any' }], controls: [{ id: 'index', type: 'formula', default: '0', label: 'Index' }], preview: true, codegen: { python: '{{result}} = list({{list}})\\n{{removed}} = {{result}}.pop(int({{index}}))', csharp: '' } },
  { type: 'list-repeat', name: 'List.Repeat', icon: '⟳', inputs: [{ id: 'item', name: 'Item', type: 'any' },{ id: 'count', name: 'Count', type: 'number' }], outputs: [{ id: 'list', name: 'List', type: 'list' }], controls: [{ id: 'count', type: 'formula', default: '5', label: 'Count' }], preview: true, codegen: { python: '{{list}} = [{{item}}] * int({{count}})', csharp: '' } },
  { type: 'list-reverse', name: 'List.Reverse', icon: '⇆', inputs: [{ id: 'list', name: 'List', type: 'list' }], outputs: [{ id: 'result', name: 'Result', type: 'list' }], controls: [], preview: true, codegen: { python: '{{result}} = list(reversed({{list}}))', csharp: '' } },
  { type: 'list-sequence', name: 'List.Sequence', icon: '⋯', inputs: [{ id: 'start', name: 'Start', type: 'number' },{ id: 'step', name: 'Step', type: 'number' },{ id: 'count', name: 'Count', type: 'number' }], outputs: [{ id: 'list', name: 'List', type: 'list' }], controls: [{ id: 'start', type: 'formula', default: '0', label: 'Start' },{ id: 'step', type: 'formula', default: '1', label: 'Step' },{ id: 'count', type: 'formula', default: '10', label: 'Count' }], preview: true, codegen: { python: '{{list}} = [{{start}} + {{step}} * i for i in range(int({{count}}))]', csharp: '' } },
  { type: 'list-shuffle', name: 'List.Shuffle', icon: '⤮', inputs: [{ id: 'list', name: 'List', type: 'list' },{ id: 'seed', name: 'Seed', type: 'number' }], outputs: [{ id: 'result', name: 'Result', type: 'list' }], controls: [{ id: 'seed', type: 'formula', default: '0', label: 'Seed' }], preview: true, codegen: { python: 'import random\\n_rng=random.Random(int({{seed}}))\\n{{result}}=list({{list}})\\n_rng.shuffle({{result}})', csharp: '' } },
  { type: 'list-skip', name: 'List.Skip', icon: '⊬', inputs: [{ id: 'list', name: 'List', type: 'list' },{ id: 'count', name: 'Count', type: 'number' }], outputs: [{ id: 'result', name: 'Result', type: 'list' }], controls: [{ id: 'count', type: 'formula', default: '1', label: 'Count' }], preview: true, codegen: { python: '{{result}} = {{list}}[int({{count}}):]', csharp: '' } },
  { type: 'list-slice', name: 'List.Slice', icon: '[:]', inputs: [{ id: 'list', name: 'List', type: 'list' },{ id: 'from', name: 'From', type: 'number' },{ id: 'to', name: 'To', type: 'number' }], outputs: [{ id: 'result', name: 'Result', type: 'list' }], controls: [{ id: 'from', type: 'formula', default: '0', label: 'From' },{ id: 'to', type: 'formula', default: '5', label: 'To' }], preview: true, codegen: { python: '{{result}} = {{list}}[int({{from}}):int({{to}})]', csharp: '' } },
  { type: 'list-sort', name: 'List.Sort', icon: '↕', inputs: [{ id: 'list', name: 'List', type: 'list' }], outputs: [{ id: 'result', name: 'Result', type: 'list' }], controls: [{ id: 'desc', type: 'dropdown', options: ['Ascending','Descending'], default: 'Ascending', label: 'Order' }], preview: true, codegen: { python: '{{result}} = sorted({{list}}, reverse={{desc}})', csharp: '' } },
  { type: 'list-sum', name: 'List.Sum', icon: 'Σ', inputs: [{ id: 'list', name: 'List', type: 'list' }], outputs: [{ id: 'result', name: 'Result', type: 'number' }], controls: [], preview: true, codegen: { python: '{{result}} = sum({{list}})', csharp: '' } },
  { type: 'list-take', name: 'List.Take', icon: '⊢n', inputs: [{ id: 'list', name: 'List', type: 'list' },{ id: 'count', name: 'Count', type: 'number' }], outputs: [{ id: 'result', name: 'Result', type: 'list' }], controls: [{ id: 'count', type: 'formula', default: '5', label: 'Count' }], preview: true, codegen: { python: '{{result}} = {{list}}[:int({{count}})]', csharp: '' } },
  { type: 'list-transpose', name: 'List.Transpose', icon: '⊤', inputs: [{ id: 'list', name: 'List', type: 'list' }], outputs: [{ id: 'result', name: 'Result', type: 'list' }], controls: [], preview: true, codegen: { python: '{{result}} = list(map(list, zip(*{{list}})))', csharp: '' } },
  { type: 'list-unique', name: 'List.Unique', icon: '∪', inputs: [{ id: 'list', name: 'List', type: 'list' }], outputs: [{ id: 'result', name: 'Result', type: 'list' }], controls: [], preview: true, codegen: { python: '{{result}} = list(dict.fromkeys({{list}}))', csharp: '' } },
  { type: 'list-zip', name: 'List.Zip', icon: '⊕', inputs: [{ id: 'listA', name: 'List A', type: 'list' },{ id: 'listB', name: 'List B', type: 'list' }], outputs: [{ id: 'result', name: 'Result', type: 'list' }], controls: [], preview: true, codegen: { python: '{{result}} = list(zip({{listA}}, {{listB}}))', csharp: '' } }
] });

// ═══════════════════════════════════════
// 6. LOGIC
// ═══════════════════════════════════════
NODE_LIBRARY.categories.push({ id: 'logic', name: 'Logic', color: '#f38ba8', icon: '⊻', nodes: [
  { type: 'logic-and', name: 'Logic.AND', icon: '∧', inputs: [{ id: 'a', name: 'A', type: 'boolean' },{ id: 'b', name: 'B', type: 'boolean' }], outputs: [{ id: 'result', name: 'Result', type: 'boolean' }], controls: [{ id: 'a', type: 'formula', default: 'true', label: 'A' },{ id: 'b', type: 'formula', default: 'true', label: 'B' }], preview: true, codegen: { python: '{{result}} = {{a}} and {{b}}', csharp: '' } },
  { type: 'logic-compare', name: 'Logic.Compare', icon: '≷', inputs: [{ id: 'a', name: 'A', type: 'any' },{ id: 'b', name: 'B', type: 'any' }], outputs: [{ id: 'result', name: 'Result', type: 'boolean' }], controls: [{ id: 'a', type: 'formula', default: '0', label: 'A' },{ id: 'b', type: 'formula', default: '0', label: 'B' },{ id: 'op', type: 'dropdown', options: ['==','!=','<','>','<=','>='], default: '==', label: 'Operator' }], preview: true, codegen: { python: '{{result}} = {{a}} {{op}} {{b}}', csharp: '' } },
  { type: 'logic-gate', name: 'Logic.Gate', icon: '⊳', inputs: [{ id: 'value', name: 'Value', type: 'any' },{ id: 'pass', name: 'Pass', type: 'boolean' }], outputs: [{ id: 'result', name: 'Result', type: 'any' }], controls: [{ id: 'pass', type: 'formula', default: 'true', label: 'Pass' }], preview: true, codegen: { python: '{{result}} = {{value}} if {{pass}} else None', csharp: '' } },
  { type: 'logic-if', name: 'Logic.If', icon: '?', inputs: [{ id: 'condition', name: 'Test', type: 'boolean' },{ id: 'ifTrue', name: 'True', type: 'any' },{ id: 'ifFalse', name: 'False', type: 'any' }], outputs: [{ id: 'result', name: 'Result', type: 'any' }], controls: [{ id: 'condition', type: 'formula', default: 'true', label: 'Test' },{ id: 'ifTrue', type: 'formula', default: '1', label: 'True' },{ id: 'ifFalse', type: 'formula', default: '0', label: 'False' }], preview: true, codegen: { python: '{{result}} = {{ifTrue}} if {{condition}} else {{ifFalse}}', csharp: '' } },
  { type: 'logic-isnull', name: 'Logic.IsNull', icon: '∅', inputs: [{ id: 'value', name: 'Value', type: 'any' }], outputs: [{ id: 'result', name: 'Result', type: 'boolean' }], controls: [], preview: true, codegen: { python: '{{result}} = {{value}} is None', csharp: '' } },
  { type: 'logic-not', name: 'Logic.NOT', icon: '¬', inputs: [{ id: 'value', name: 'Value', type: 'boolean' }], outputs: [{ id: 'result', name: 'Result', type: 'boolean' }], controls: [{ id: 'value', type: 'formula', default: 'true', label: 'Value' }], preview: true, codegen: { python: '{{result}} = not {{value}}', csharp: '' } },
  { type: 'logic-or', name: 'Logic.OR', icon: '∨', inputs: [{ id: 'a', name: 'A', type: 'boolean' },{ id: 'b', name: 'B', type: 'boolean' }], outputs: [{ id: 'result', name: 'Result', type: 'boolean' }], controls: [{ id: 'a', type: 'formula', default: 'true', label: 'A' },{ id: 'b', type: 'formula', default: 'false', label: 'B' }], preview: true, codegen: { python: '{{result}} = {{a}} or {{b}}', csharp: '' } },
  { type: 'logic-xor', name: 'Logic.XOR', icon: '⊻', inputs: [{ id: 'a', name: 'A', type: 'boolean' },{ id: 'b', name: 'B', type: 'boolean' }], outputs: [{ id: 'result', name: 'Result', type: 'boolean' }], controls: [{ id: 'a', type: 'formula', default: 'true', label: 'A' },{ id: 'b', type: 'formula', default: 'false', label: 'B' }], preview: true, codegen: { python: '{{result}} = ({{a}} or {{b}}) and not ({{a}} and {{b}})', csharp: '' } }
] });

// ═══════════════════════════════════════
// 7. MATH (16 nodes, A→Z)
// ═══════════════════════════════════════
NODE_LIBRARY.categories.push({ id: 'math', name: 'Math', color: '#a6e3a1', icon: 'Σ', nodes: [
  { type: 'math-abs', name: 'Math.Absolute', icon: '|x|', inputs: [{ id: 'a', name: 'Value', type: 'number' }], outputs: [{ id: 'result', name: 'Result', type: 'number' }], controls: [{ id: 'a', type: 'formula', default: '0', label: 'Value' }], preview: true, codegen: { python: '{{result}} = abs({{a}})', csharp: '' } },
  { type: 'math-add', name: 'Math.Add', icon: '+', inputs: [{ id: 'a', name: 'A', type: 'number' },{ id: 'b', name: 'B', type: 'number' }], outputs: [{ id: 'result', name: 'Result', type: 'number' }], controls: [{ id: 'a', type: 'formula', default: '0', label: 'A' },{ id: 'b', type: 'formula', default: '0', label: 'B' }], lacing: { mode: 'shortest' }, preview: true, codegen: { python: '{{result}} = {{a}} + {{b}}', csharp: '' } },
  { type: 'math-ceil', name: 'Math.Ceiling', icon: '⌈x⌉', inputs: [{ id: 'a', name: 'Value', type: 'number' }], outputs: [{ id: 'result', name: 'Result', type: 'number' }], controls: [{ id: 'a', type: 'formula', default: '0', label: 'Value' }], preview: true, codegen: { python: 'import math\\n{{result}} = math.ceil({{a}})', csharp: '' } },
  { type: 'math-clamp', name: 'Math.Clamp', icon: '⊏⊐', inputs: [{ id: 'value', name: 'Value', type: 'number' }], outputs: [{ id: 'result', name: 'Result', type: 'number' }], controls: [{ id: 'value', type: 'formula', default: '0', label: 'Value' },{ id: 'min', type: 'formula', default: '0', label: 'Min' },{ id: 'max', type: 'formula', default: '1', label: 'Max' }], preview: true, codegen: { python: '{{result}} = max({{min}}, min({{max}}, {{value}}))', csharp: '' } },
  { type: 'math-divide', name: 'Math.Divide', icon: '÷', inputs: [{ id: 'a', name: 'A', type: 'number' },{ id: 'b', name: 'B', type: 'number' }], outputs: [{ id: 'result', name: 'Result', type: 'number' }], controls: [{ id: 'a', type: 'formula', default: '1', label: 'A' },{ id: 'b', type: 'formula', default: '1', label: 'B' }], lacing: { mode: 'shortest' }, preview: true, codegen: { python: '{{result}} = {{a}} / {{b}}', csharp: '' } },
  { type: 'math-floor', name: 'Math.Floor', icon: '⌊x⌋', inputs: [{ id: 'a', name: 'Value', type: 'number' }], outputs: [{ id: 'result', name: 'Result', type: 'number' }], controls: [{ id: 'a', type: 'formula', default: '0', label: 'Value' }], preview: true, codegen: { python: 'import math\\n{{result}} = math.floor({{a}})', csharp: '' } },
  { type: 'math-max', name: 'Math.Max', icon: '↑', inputs: [{ id: 'a', name: 'A', type: 'number' },{ id: 'b', name: 'B', type: 'number' }], outputs: [{ id: 'result', name: 'Result', type: 'number' }], controls: [], preview: true, codegen: { python: '{{result}} = max({{a}}, {{b}})', csharp: '' } },
  { type: 'math-min', name: 'Math.Min', icon: '↓', inputs: [{ id: 'a', name: 'A', type: 'number' },{ id: 'b', name: 'B', type: 'number' }], outputs: [{ id: 'result', name: 'Result', type: 'number' }], controls: [], preview: true, codegen: { python: '{{result}} = min({{a}}, {{b}})', csharp: '' } },
  { type: 'math-modulo', name: 'Math.Modulo', icon: '%', inputs: [{ id: 'a', name: 'A', type: 'number' },{ id: 'b', name: 'B', type: 'number' }], outputs: [{ id: 'result', name: 'Result', type: 'number' }], controls: [{ id: 'a', type: 'formula', default: '0', label: 'A' },{ id: 'b', type: 'formula', default: '1', label: 'B' }], preview: true, codegen: { python: '{{result}} = {{a}} % {{b}}', csharp: '' } },
  { type: 'math-multiply', name: 'Math.Multiply', icon: '×', inputs: [{ id: 'a', name: 'A', type: 'number' },{ id: 'b', name: 'B', type: 'number' }], outputs: [{ id: 'result', name: 'Result', type: 'number' }], controls: [{ id: 'a', type: 'formula', default: '1', label: 'A' },{ id: 'b', type: 'formula', default: '1', label: 'B' }], lacing: { mode: 'shortest' }, preview: true, codegen: { python: '{{result}} = {{a}} * {{b}}', csharp: '' } },
  { type: 'math-negate', name: 'Math.Negate', icon: '±', inputs: [{ id: 'a', name: 'Value', type: 'number' }], outputs: [{ id: 'result', name: 'Result', type: 'number' }], controls: [{ id: 'a', type: 'formula', default: '0', label: 'Value' }], preview: true, codegen: { python: '{{result}} = -{{a}}', csharp: '' } },
  { type: 'math-power', name: 'Math.Power', icon: '^', inputs: [{ id: 'base', name: 'Base', type: 'number' },{ id: 'exp', name: 'Exp', type: 'number' }], outputs: [{ id: 'result', name: 'Result', type: 'number' }], controls: [{ id: 'base', type: 'formula', default: '2', label: 'Base' },{ id: 'exp', type: 'formula', default: '2', label: 'Exp' }], preview: true, codegen: { python: '{{result}} = math.pow({{base}}, {{exp}})', csharp: '' } },
  { type: 'math-reciprocal', name: 'Math.Reciprocal', icon: '1/x', inputs: [{ id: 'a', name: 'Value', type: 'number' }], outputs: [{ id: 'result', name: 'Result', type: 'number' }], controls: [{ id: 'a', type: 'formula', default: '1', label: 'Value' }], preview: true, codegen: { python: '{{result}} = 1 / {{a}}', csharp: '' } },
  { type: 'math-remap', name: 'Math.Remap', icon: '↔', inputs: [{ id: 'value', name: 'Value', type: 'any' }], outputs: [{ id: 'result', name: 'Result', type: 'any' }], controls: [{ id: 'value', type: 'formula', default: '0.5', label: 'Value' },{ id: 'fromMin', type: 'formula', default: 'auto', label: 'From Min' },{ id: 'fromMax', type: 'formula', default: 'auto', label: 'From Max' },{ id: 'toMin', type: 'formula', default: '0', label: 'To Min' },{ id: 'toMax', type: 'formula', default: '100', label: 'To Max' }], preview: true, codegen: { python: '{{result}} = {{toMin}} + ({{value}} - {{fromMin}}) / ({{fromMax}} - {{fromMin}}) * ({{toMax}} - {{toMin}})', csharp: '' } },
  { type: 'math-round', name: 'Math.Round', icon: '≈', inputs: [{ id: 'a', name: 'Value', type: 'number' }], outputs: [{ id: 'result', name: 'Result', type: 'number' }], controls: [{ id: 'a', type: 'formula', default: '0', label: 'Value' },{ id: 'digits', type: 'formula', default: '0', label: 'Digits' }], preview: true, codegen: { python: '{{result}} = round({{a}}, int({{digits}}))', csharp: '' } },
  { type: 'math-subtract', name: 'Math.Subtract', icon: '−', inputs: [{ id: 'a', name: 'A', type: 'number' },{ id: 'b', name: 'B', type: 'number' }], outputs: [{ id: 'result', name: 'Result', type: 'number' }], controls: [{ id: 'a', type: 'formula', default: '0', label: 'A' },{ id: 'b', type: 'formula', default: '0', label: 'B' }], lacing: { mode: 'shortest' }, preview: true, codegen: { python: '{{result}} = {{a}} - {{b}}', csharp: '' } }
] });

// ═══════════════════════════════════════
// 8. MODELING
// ═══════════════════════════════════════
NODE_LIBRARY.categories.push({ id: 'modeling', name: 'Modeling', color: '#f5c2e7', icon: '⚙', nodes: [
  { type: 'op-boolean-intersect', name: 'Boolean Intersect', icon: '∩', inputs: [{ id: 'a', name: 'Solid A', type: 'mesh' },{ id: 'b', name: 'Solid B', type: 'mesh' }], outputs: [{ id: 'result', name: 'Result', type: 'mesh' }], controls: [], preview: true, codegen: { python: '{{result}} = Geo.booleanIntersect({{a}}, {{b}})', csharp: '' } },
  { type: 'op-boolean-subtract', name: 'Boolean Subtract', icon: '∖', inputs: [{ id: 'a', name: 'Solid A', type: 'mesh' },{ id: 'b', name: 'Solid B', type: 'mesh' }], outputs: [{ id: 'result', name: 'Result', type: 'mesh' }], controls: [], preview: true, codegen: { python: '{{result}} = Geo.booleanSubtract({{a}}, {{b}})', csharp: '' } },
  { type: 'op-boolean-union', name: 'Boolean Union', icon: '∪', inputs: [{ id: 'a', name: 'Solid A', type: 'mesh' },{ id: 'b', name: 'Solid B', type: 'mesh' }], outputs: [{ id: 'result', name: 'Result', type: 'mesh' }], controls: [], preview: true, codegen: { python: '{{result}} = Geo.booleanUnion({{a}}, {{b}})', csharp: '' } },
  { type: 'op-combine-all', name: 'Combine All', icon: '⊕', inputs: [{ id: 'meshes', name: 'Meshes', type: 'list' }], outputs: [{ id: 'result', name: 'Result', type: 'mesh' }], controls: [], preview: true, codegen: { python: '{{result}} = Geo.combineAll({{meshes}})', csharp: '' } },
  { type: 'op-extrude', name: 'Extrude', icon: '⬆', inputs: [{ id: 'curve', name: 'Curve', type: 'any' },{ id: 'vector', name: 'Direction', type: 'vector' }], outputs: [{ id: 'solid', name: 'Solid', type: 'mesh' }], controls: [], preview: true, codegen: { python: '{{solid}} = Geo.extrude({{curve}}, {{vector}})', csharp: '' } },
  { type: 'op-loft', name: 'Loft', icon: '⊟', inputs: [{ id: 'profiles', name: 'Profiles', type: 'list' }], outputs: [{ id: 'solid', name: 'Solid', type: 'mesh' }], controls: [], preview: true, codegen: { python: '{{solid}} = Geo.loft({{profiles}})', csharp: '' } },
  { type: 'op-offset', name: 'Offset Curve', icon: '⟿', inputs: [{ id: 'curve', name: 'Curve', type: 'any' },{ id: 'distance', name: 'Distance', type: 'number' }], outputs: [{ id: 'result', name: 'Result', type: 'curve' }], controls: [], preview: true, codegen: { python: '{{result}} = Geo.offsetCurve({{curve}}, {{distance}})', csharp: '' } },
  { type: 'op-pipe', name: 'Pipe', icon: '◯', inputs: [{ id: 'curve', name: 'Curve', type: 'any' },{ id: 'radius', name: 'Radius', type: 'number' }], outputs: [{ id: 'solid', name: 'Solid', type: 'mesh' }], controls: [], preview: true, codegen: { python: '{{solid}} = Geo.pipe({{curve}}, {{radius}})', csharp: '' } },
  { type: 'op-point-grid', name: 'Point Grid', icon: '⊞', inputs: [{ id: 'origin', name: 'Origin', type: 'point' },{ id: 'uCount', name: 'U Count', type: 'number' },{ id: 'vCount', name: 'V Count', type: 'number' },{ id: 'spacing', name: 'Spacing', type: 'number' }], outputs: [{ id: 'points', name: 'Points', type: 'list' }], controls: [], preview: true, codegen: { python: '{{points}} = Geo.pointGrid({{origin}}, Geo.Vector3(1,0,0), Geo.Vector3(0,1,0), {{uCount}}, {{vCount}}, {{spacing}}, {{spacing}})', csharp: '' } },
  { type: 'op-revolve', name: 'Revolve', icon: '↻', inputs: [{ id: 'curve', name: 'Curve', type: 'any' },{ id: 'axisOrigin', name: 'Axis Pt', type: 'point' },{ id: 'axisDir', name: 'Axis Dir', type: 'vector' },{ id: 'angle', name: 'Angle°', type: 'number' }], outputs: [{ id: 'solid', name: 'Solid', type: 'mesh' }], controls: [], preview: true, codegen: { python: '{{solid}} = Geo.revolve({{curve}}, {{axisOrigin}}, {{axisDir}}, math.radians({{angle}}))', csharp: '' } },
  { type: 'op-smooth', name: 'Smooth', icon: '〰', inputs: [{ id: 'mesh', name: 'Mesh', type: 'mesh' },{ id: 'iterations', name: 'Iterations', type: 'number' }], outputs: [{ id: 'result', name: 'Result', type: 'mesh' }], controls: [], preview: true, codegen: { python: '{{result}} = Geo.smooth({{mesh}}, {{iterations}})', csharp: '' } },
  { type: 'op-subdivide', name: 'Subdivide', icon: '◈', inputs: [{ id: 'mesh', name: 'Mesh', type: 'mesh' },{ id: 'iterations', name: 'Iterations', type: 'number' }], outputs: [{ id: 'result', name: 'Result', type: 'mesh' }], controls: [], preview: true, codegen: { python: '{{result}} = Geo.subdivide({{mesh}}, {{iterations}})', csharp: '' } },
  { type: 'op-sweep', name: 'Sweep', icon: '⤻', inputs: [{ id: 'profile', name: 'Profile', type: 'any' },{ id: 'path', name: 'Path', type: 'any' }], outputs: [{ id: 'solid', name: 'Solid', type: 'mesh' }], controls: [], preview: true, codegen: { python: '{{solid}} = Geo.sweep({{profile}}, {{path}})', csharp: '' } },
  { type: 'op-thicken', name: 'Thicken', icon: '⊡', inputs: [{ id: 'mesh', name: 'Mesh', type: 'mesh' },{ id: 'thickness', name: 'Thickness', type: 'number' }], outputs: [{ id: 'result', name: 'Result', type: 'mesh' }], controls: [], preview: true, codegen: { python: '{{result}} = Geo.thicken({{mesh}}, {{thickness}})', csharp: '' } },
  { type: 'op-trim', name: 'Trim Line', icon: '✂', inputs: [{ id: 'line', name: 'Line', type: 'line' },{ id: 't0', name: 'Start t', type: 'number' },{ id: 't1', name: 'End t', type: 'number' }], outputs: [{ id: 'result', name: 'Result', type: 'line' }], controls: [], preview: true, codegen: { python: '{{result}} = Geo.trimLine({{line}}, {{t0}}, {{t1}})', csharp: '' } }
] });

// ═══════════════════════════════════════
// 9. OUTPUT
// ═══════════════════════════════════════
NODE_LIBRARY.categories.push({ id: 'output', name: 'Output', color: '#f9e2af', icon: '◎', nodes: [
  { type: 'output-chart', name: 'Chart', icon: '📊', inputs: [{ id: 'data', name: 'Data', type: 'list' }], outputs: [], controls: [{ id: 'chartType', type: 'dropdown', options: ['Bar','Line','Pie'], default: 'Bar', label: 'Type' }], preview: true, codegen: { python: 'plot_chart({{data}}, chart_type="{{ctrl.chartType}}")', csharp: '' } },
  { type: 'output-log', name: 'Console Log', icon: '⊳', inputs: [{ id: 'value', name: 'Value', type: 'any' }], outputs: [], controls: [], preview: true, codegen: { python: 'print({{value}})', csharp: '' } },
  { type: 'output-display', name: 'Display', icon: '🖥', inputs: [{ id: 'value', name: 'Value', type: 'any' }], outputs: [], controls: [{ id: 'format', type: 'dropdown', options: ['Auto','JSON','Table'], default: 'Auto', label: 'Format' }], preview: true, codegen: { python: 'print({{value}})', csharp: '' } },
  { type: 'output-export', name: 'Export', icon: '📤', inputs: [{ id: 'data', name: 'Data', type: 'any' }], outputs: [], controls: [{ id: 'fmt', type: 'dropdown', options: ['JSON','CSV','Text'], default: 'JSON', label: 'Format' }], preview: true, codegen: { python: 'export_data({{data}}, format="{{ctrl.fmt}}")', csharp: '' } },
  { type: 'output-watch', name: 'Watch', icon: '👁', inputs: [{ id: 'value', name: 'Value', type: 'any' }], outputs: [], controls: [], preview: true, codegen: { python: 'print({{value}})', csharp: '' } }
] });

// ═══════════════════════════════════════
// 10. PARAMETRIC FORMS
// ═══════════════════════════════════════
NODE_LIBRARY.categories.push({ id: 'parametric', name: 'Parametric Forms', color: '#cba6f7', icon: '✧', nodes: [
  { type: 'param-catenary', name: 'Catenary Shell', icon: '⌓', inputs: [{ id: 'span', name: 'Span', type: 'number' },{ id: 'height', name: 'Height', type: 'number' }], outputs: [{ id: 'mesh', name: 'Mesh', type: 'mesh' }], controls: [], preview: true, codegen: { python: '{{mesh}} = Geo.createCatenaryShell({{span}}, {{height}})', csharp: '' } },
  { type: 'param-dini', name: 'Dini Surface', icon: '⊘', inputs: [{ id: 'a', name: 'A', type: 'number' },{ id: 'b', name: 'B (twist)', type: 'number' }], outputs: [{ id: 'mesh', name: 'Mesh', type: 'mesh' }], controls: [], preview: true, codegen: { python: '{{mesh}} = Geo.createDiniSurface({{a}}, {{b}})', csharp: '' } },
  { type: 'param-enneper', name: 'Enneper Surface', icon: '≈', inputs: [{ id: 'scale', name: 'Scale', type: 'number' }], outputs: [{ id: 'mesh', name: 'Mesh', type: 'mesh' }], controls: [], preview: true, codegen: { python: '{{mesh}} = Geo.createEnneperSurface({{scale}})', csharp: '' } },
  { type: 'param-gyroid', name: 'Gyroid', icon: '⎈', inputs: [{ id: 'scale', name: 'Scale', type: 'number' }], outputs: [{ id: 'mesh', name: 'Mesh', type: 'mesh' }], controls: [], preview: true, codegen: { python: '{{mesh}} = Geo.createGyroid({{scale}})', csharp: '' } },
  { type: 'param-hypar', name: 'HyPar (Saddle)', icon: '⌢', inputs: [{ id: 'width', name: 'Width', type: 'number' },{ id: 'depth', name: 'Depth', type: 'number' },{ id: 'curvature', name: 'Curvature', type: 'number' }], outputs: [{ id: 'mesh', name: 'Mesh', type: 'mesh' }], controls: [], preview: true, codegen: { python: '{{mesh}} = Geo.createHyperbolicParaboloid({{width}}, {{depth}}, {{curvature}})', csharp: '' } },
  { type: 'param-hyperboloid', name: 'Hyperboloid', icon: '⧘', inputs: [{ id: 'radius', name: 'Radius', type: 'number' },{ id: 'waist', name: 'Waist R', type: 'number' },{ id: 'height', name: 'Height', type: 'number' }], outputs: [{ id: 'mesh', name: 'Mesh', type: 'mesh' }], controls: [], preview: true, codegen: { python: '{{mesh}} = Geo.createHyperboloid({{radius}}, {{waist}}, {{height}})', csharp: '' } },
  { type: 'param-klein', name: 'Klein Bottle', icon: '∞', inputs: [{ id: 'scale', name: 'Scale', type: 'number' }], outputs: [{ id: 'mesh', name: 'Mesh', type: 'mesh' }], controls: [], preview: true, codegen: { python: '{{mesh}} = Geo.createKleinBottle({{scale}})', csharp: '' } },
  { type: 'param-mobius', name: 'Möbius Strip', icon: '∞', inputs: [{ id: 'radius', name: 'Radius', type: 'number' },{ id: 'width', name: 'Width', type: 'number' }], outputs: [{ id: 'mesh', name: 'Mesh', type: 'mesh' }], controls: [], preview: true, codegen: { python: '{{mesh}} = Geo.createMobiusStrip({{radius}}, {{width}})', csharp: '' } },
  { type: 'param-seashell', name: 'Seashell', icon: '🐚', inputs: [{ id: 'turns', name: 'Turns', type: 'number' },{ id: 'growth', name: 'Growth', type: 'number' }], outputs: [{ id: 'mesh', name: 'Mesh', type: 'mesh' }], controls: [], preview: true, codegen: { python: '{{mesh}} = Geo.createSeashell({{turns}}, {{growth}})', csharp: '' } }
] });

// ═══════════════════════════════════════
// 11. PATTERNS
// ═══════════════════════════════════════
NODE_LIBRARY.categories.push({ id: 'patterns', name: 'Patterns', color: '#f5c2e7', icon: '◈', nodes: [
  { type: 'field-attractor', name: 'Attractor Deform', icon: '⊕', inputs: [{ id: 'mesh', name: 'Mesh', type: 'mesh' },{ id: 'attractors', name: 'Attractor Pts', type: 'list' },{ id: 'radius', name: 'Radius', type: 'number' },{ id: 'strength', name: 'Strength', type: 'number' }], outputs: [{ id: 'result', name: 'Result', type: 'mesh' }], controls: [], preview: true, codegen: { python: '{{result}} = Geo.attractorDeform({{mesh}}, {{attractors}}, {{radius}}, {{strength}})', csharp: '' } },
  { type: 'pat-diamond-grid', name: 'Diamond Grid', icon: '◇', inputs: [{ id: 'origin', name: 'Origin', type: 'point' },{ id: 'width', name: 'Width', type: 'number' },{ id: 'height', name: 'Height', type: 'number' },{ id: 'rows', name: 'Rows', type: 'number' },{ id: 'cols', name: 'Cols', type: 'number' }], outputs: [{ id: 'cells', name: 'Cells', type: 'list' }], controls: [], preview: true, codegen: { python: '{{cells}} = Geo.diamondGrid({{origin}}, {{width}}, {{height}}, {{rows}}, {{cols}})', csharp: '' } },
  { type: 'pat-facade-panels', name: 'Facade Panels', icon: '▦', inputs: [{ id: 'mesh', name: 'Surface', type: 'mesh' },{ id: 'uPanels', name: 'U Panels', type: 'number' },{ id: 'vPanels', name: 'V Panels', type: 'number' }], outputs: [{ id: 'panels', name: 'Panels', type: 'list' }], controls: [], preview: true, codegen: { python: '{{panels}} = Geo.facadePanels({{mesh}}, {{uPanels}}, {{vPanels}})', csharp: '' } },
  { type: 'pat-fbm', name: 'FBM Noise', icon: '≈', inputs: [{ id: 'x', name: 'X', type: 'number' },{ id: 'y', name: 'Y', type: 'number' },{ id: 'z', name: 'Z', type: 'number' },{ id: 'octaves', name: 'Octaves', type: 'number' }], outputs: [{ id: 'value', name: 'Value', type: 'number' }], controls: [], preview: true, codegen: { python: '{{value}} = Geo.fbm({{x}}, {{y}}, {{z}}, {{octaves}})', csharp: '' } },
  { type: 'pat-fibonacci-sphere', name: 'Fibonacci Sphere', icon: '◉', inputs: [{ id: 'count', name: 'Count', type: 'number' },{ id: 'radius', name: 'Radius', type: 'number' }], outputs: [{ id: 'points', name: 'Points', type: 'list' }], controls: [], preview: true, codegen: { python: '{{points}} = Geo.fibonacciSphere({{count}}, {{radius}})', csharp: '' } },
  { type: 'pat-hex-grid', name: 'Hex Grid', icon: '⎔', inputs: [{ id: 'origin', name: 'Origin', type: 'point' },{ id: 'radius', name: 'Radius', type: 'number' },{ id: 'rows', name: 'Rows', type: 'number' },{ id: 'cols', name: 'Cols', type: 'number' }], outputs: [{ id: 'cells', name: 'Cells', type: 'list' }], controls: [], preview: true, codegen: { python: '{{cells}} = Geo.hexGrid({{origin}}, {{radius}}, {{rows}}, {{cols}})', csharp: '' } },
  { type: 'pat-noise-deform', name: 'Noise Deform', icon: '↝', inputs: [{ id: 'mesh', name: 'Mesh', type: 'mesh' },{ id: 'amplitude', name: 'Amplitude', type: 'number' },{ id: 'frequency', name: 'Frequency', type: 'number' }], outputs: [{ id: 'result', name: 'Result', type: 'mesh' }], controls: [], preview: true, codegen: { python: '{{result}} = Geo.noiseDeform({{mesh}}, {{amplitude}}, {{frequency}})', csharp: '' } },
  { type: 'pat-perlin2', name: 'Perlin 2D', icon: '〰', inputs: [{ id: 'x', name: 'X', type: 'number' },{ id: 'y', name: 'Y', type: 'number' }], outputs: [{ id: 'value', name: 'Value', type: 'number' }], controls: [], preview: true, codegen: { python: '{{value}} = Geo.perlin2({{x}}, {{y}})', csharp: '' } },
  { type: 'pat-perlin3', name: 'Perlin 3D', icon: '〰', inputs: [{ id: 'x', name: 'X', type: 'number' },{ id: 'y', name: 'Y', type: 'number' },{ id: 'z', name: 'Z', type: 'number' }], outputs: [{ id: 'value', name: 'Value', type: 'number' }], controls: [], preview: true, codegen: { python: '{{value}} = Geo.perlin3({{x}}, {{y}}, {{z}})', csharp: '' } },
  { type: 'pat-phyllotaxis', name: 'Phyllotaxis', icon: '✿', inputs: [{ id: 'count', name: 'Count', type: 'number' },{ id: 'radius', name: 'Radius', type: 'number' }], outputs: [{ id: 'points', name: 'Points', type: 'list' }], controls: [], preview: true, codegen: { python: '{{points}} = Geo.phyllotaxis({{count}}, {{radius}})', csharp: '' } },
  { type: 'pat-point-attractor', name: 'Point Attractor', icon: '◎', inputs: [{ id: 'point', name: 'Point', type: 'point' },{ id: 'attractor', name: 'Attractor', type: 'point' },{ id: 'radius', name: 'Radius', type: 'number' },{ id: 'falloff', name: 'Falloff', type: 'number' }], outputs: [{ id: 'influence', name: 'Influence', type: 'number' }], controls: [], preview: true, codegen: { python: '{{influence}} = Geo.pointAttractor({{point}}, {{attractor}}, {{radius}}, {{falloff}})', csharp: '' } },
  { type: 'field-sin', name: 'Sin Deform', icon: '∿', inputs: [{ id: 'mesh', name: 'Mesh', type: 'mesh' },{ id: 'amplitude', name: 'Amplitude', type: 'number' },{ id: 'frequency', name: 'Frequency', type: 'number' }], outputs: [{ id: 'result', name: 'Result', type: 'mesh' }], controls: [{ id: 'axis', type: 'dropdown', options: ['z','x','y'], default: 'z', label: 'Axis' }], preview: true, codegen: { python: '{{result}} = Geo.sinDeform({{mesh}}, {{amplitude}}, {{frequency}}, "{{ctrl.axis}}")', csharp: '' } },
  { type: 'pat-voronoi-mesh', name: 'Voronoi Mesh', icon: '⬡', inputs: [{ id: 'sites', name: 'Sites', type: 'list' },{ id: 'height', name: 'Height', type: 'number' },{ id: 'gap', name: 'Gap', type: 'number' }], outputs: [{ id: 'meshes', name: 'Meshes', type: 'list' }], controls: [], preview: true, codegen: { python: '{{meshes}} = Geo.voronoiMesh({{sites}}, None, {{height}}, {{gap}})', csharp: '' } },
  { type: 'pat-voronoi-outlines', name: 'Voronoi Outlines', icon: '⬡', inputs: [{ id: 'sites', name: 'Sites', type: 'list' }], outputs: [{ id: 'outlines', name: 'Outlines', type: 'list' }], controls: [], preview: true, codegen: { python: '{{outlines}} = Geo.voronoiOutlines({{sites}}, None, 0.5)', csharp: '' } }
] });

// ═══════════════════════════════════════
// 12. POINT
// ═══════════════════════════════════════
NODE_LIBRARY.categories.push({ id: 'point', name: 'Point', color: '#89b4fa', icon: '•', nodes: [
  { type: 'geo-distance', name: 'Distance', icon: '⟷', inputs: [{ id: 'a', name: 'Point A', type: 'point' },{ id: 'b', name: 'Point B', type: 'point' }], outputs: [{ id: 'distance', name: 'Distance', type: 'number' }], controls: [], preview: true, codegen: { python: '{{distance}} = math.dist({{a}}, {{b}})', csharp: '' } },
  { type: 'point-bycoordinates', name: 'Point.ByCoordinates', icon: '•', inputs: [{ id: 'x', name: 'X', type: 'number' },{ id: 'y', name: 'Y', type: 'number' },{ id: 'z', name: 'Z', type: 'number' }], outputs: [{ id: 'point', name: 'Point', type: 'point' }], controls: [{ id: 'x', type: 'formula', default: '0', label: 'X', axis: 'x' },{ id: 'y', type: 'formula', default: '0', label: 'Y', axis: 'y' },{ id: 'z', type: 'formula', default: '0', label: 'Z', axis: 'z' }], preview: true, codegen: { python: '{{point}} = Geo.Point3({{x}}, {{y}}, {{z}})', csharp: '' } },
  { type: 'point-deconstruct', name: 'Point.Deconstruct', icon: '⊙', inputs: [{ id: 'point', name: 'Point', type: 'point' }], outputs: [{ id: 'x', name: 'X', type: 'number' },{ id: 'y', name: 'Y', type: 'number' },{ id: 'z', name: 'Z', type: 'number' }], controls: [], preview: true, codegen: { python: '{{x}} = {{point}}.x\\n{{y}} = {{point}}.y\\n{{z}} = {{point}}.z', csharp: '' } },
  { type: 'point-origin', name: 'Point.Origin', icon: '⊕', inputs: [], outputs: [{ id: 'point', name: 'Point', type: 'point' }], controls: [], preview: true, codegen: { python: '{{point}} = Geo.Point3(0, 0, 0)', csharp: '' } },
  { type: 'point-x', name: 'Point.X', icon: 'X', inputs: [{ id: 'point', name: 'Point', type: 'point' }], outputs: [{ id: 'x', name: 'X', type: 'number' }], controls: [], preview: true, codegen: { python: '{{x}} = {{point}}.x', csharp: '' } },
  { type: 'point-y', name: 'Point.Y', icon: 'Y', inputs: [{ id: 'point', name: 'Point', type: 'point' }], outputs: [{ id: 'y', name: 'Y', type: 'number' }], controls: [], preview: true, codegen: { python: '{{y}} = {{point}}.y', csharp: '' } },
  { type: 'point-z', name: 'Point.Z', icon: 'Z', inputs: [{ id: 'point', name: 'Point', type: 'point' }], outputs: [{ id: 'z', name: 'Z', type: 'number' }], controls: [], preview: true, codegen: { python: '{{z}} = {{point}}.z', csharp: '' } }
] });

// ═══════════════════════════════════════
// 13. REVIT (3 typed element nodes only)
// ═══════════════════════════════════════
NODE_LIBRARY.categories.push({ id: 'revit', name: 'Revit', color: '#89dceb', icon: '🏗', nodes: [
  { type: 'revit-all-elements-view', name: 'Revit.AllElementsInActiveView', icon: '👁', inputs: [], outputs: [{ id: 'elements', name: 'Elements', type: 'list' },{ id: 'count', name: 'Count', type: 'number' }], controls: [], preview: true, codegen: { python: '{{elements}} = RevitBridge.getAllElements()\\n{{count}} = len({{elements}})\\nprint(f"Found {{{count}}} elements in active view")' } },
  { type: 'revit-all-of-category', name: 'Revit.AllElementsOfCategory', icon: '📦', inputs: [], outputs: [{ id: 'elements', name: 'Elements', type: 'list' },{ id: 'count', name: 'Count', type: 'number' }], controls: [{ id: 'category', type: 'dropdown', options: ['Walls','Floors','Roofs','Ceilings','Doors','Windows','Rooms','Columns','Structural Columns','Structural Framing','Furniture','Generic Models','Mechanical Equipment','Plumbing Fixtures','Electrical Fixtures','Electrical Equipment','Pipes','Ducts','Stairs','Railings','Curtain Panels','Grids','Levels','Sheets'], default: 'Walls', label: 'Category' }], preview: true, codegen: { python: '{{elements}} = RevitBridge.getElements("{{ctrl.category}}")\\n{{count}} = len({{elements}})\\nprint(f"Found {{{count}}} {{ctrl.category}}")' } },
  { type: 'revit-element-geometries', name: 'Element.Geometries', icon: '🔷', inputs: [{ id: 'elements', name: 'Elements', type: 'list' }], outputs: [{ id: 'meshes', name: 'Meshes', type: 'list' },{ id: 'count', name: 'Count', type: 'number' }], controls: [], preview: true, codegen: { python: '{{meshes}} = RevitBridge.getGeometries({{elements}})\\n{{count}} = len({{meshes}})\\nprint(f"Extracted {{{count}}} meshes")' } },
  { type: 'revit-get-parameter-values', name: 'Revit.GetParameterValues', icon: 'P', inputs: [{ id: 'elements', name: 'Elements', type: 'list' },{ id: 'parameterName', name: 'Parameter Name', type: 'string' }], outputs: [{ id: 'values', name: 'Values', type: 'list' },{ id: 'count', name: 'Count', type: 'number' }], controls: [{ id: 'parameterName', type: 'text', default: 'Comments', label: 'Parameter Name' }], preview: true, codegen: { python: '{{values}} = RevitBridge.getParameterValues({{elements}}, "{{ctrl.parameterName}}")\\n{{count}} = len({{values}})' } },
  { type: 'revit-set-parameter-values', name: 'Revit.SetParameterValues', icon: 'P+', inputs: [{ id: 'elements', name: 'Elements', type: 'list' },{ id: 'parameterName', name: 'Parameter Name', type: 'string' },{ id: 'value', name: 'Value', type: 'any' }], outputs: [{ id: 'results', name: 'Results', type: 'list' },{ id: 'count', name: 'Count', type: 'number' },{ id: 'success', name: 'Success', type: 'boolean' }], controls: [{ id: 'parameterName', type: 'text', default: 'Comments', label: 'Parameter Name' },{ id: 'value', type: 'text', default: '', label: 'Value' }], preview: true, codegen: { python: '{{results}} = RevitBridge.setParameterValues({{elements}}, "{{ctrl.parameterName}}", "{{ctrl.value}}")\\n{{count}} = len([r for r in {{results}} if r.get("ok")])\\n{{success}} = {{count}} == len({{results}})' } },
  { type: 'revit-send-geometry', name: 'Revit.SendGeometry', icon: '⬆', inputs: [{ id: 'geometry', name: 'Geometry', type: 'any' },{ id: 'category', name: 'Category', type: 'string' },{ id: 'name', name: 'Name', type: 'string' }], outputs: [{ id: 'result', name: 'Result', type: 'any' },{ id: 'elementId', name: 'Element Id', type: 'string' },{ id: 'success', name: 'Success', type: 'boolean' }], controls: [{ id: 'category', type: 'dropdown', options: ['Generic Models','Mass','Furniture','Walls','Floors','Roofs','Ceilings','Columns','Structural Framing','Mechanical Equipment','Plumbing Fixtures','Electrical Fixtures','Electrical Equipment'], default: 'Generic Models', label: 'Category' },{ id: 'name', type: 'text', default: 'Nova Geometry', label: 'Name' }], preview: true, codegen: { python: '{{result}} = RevitBridge.sendGeometry({{geometry}}, {}, {"category": "{{ctrl.category}}", "name": "{{ctrl.name}}"})\\n{{elementId}} = {{result}}.get("data", {}).get("directShapeId")\\n{{success}} = {{result}}.get("ok") == True' } }
] });

// ═══════════════════════════════════════
// 14. SOLIDS
// ═══════════════════════════════════════
NODE_LIBRARY.categories.push({ id: 'solids', name: 'Solids', color: '#f38ba8', icon: '◆', nodes: [
  { type: 'solid-box', name: 'Box', icon: '▣', inputs: [{ id: 'center', name: 'Center', type: 'point' },{ id: 'width', name: 'Width', type: 'number' },{ id: 'depth', name: 'Depth', type: 'number' },{ id: 'height', name: 'Height', type: 'number' }], outputs: [{ id: 'solid', name: 'Solid', type: 'mesh' }], controls: [], preview: true, codegen: { python: '{{solid}} = Geo.createBox({{center}}, {{width}}, {{depth}}, {{height}})', csharp: '' } },
  { type: 'solid-cone', name: 'Cone', icon: '▲', inputs: [{ id: 'base', name: 'Base', type: 'point' },{ id: 'radius', name: 'Radius', type: 'number' },{ id: 'height', name: 'Height', type: 'number' }], outputs: [{ id: 'solid', name: 'Solid', type: 'mesh' }], controls: [], preview: true, codegen: { python: '{{solid}} = Geo.createCone({{base}}, {{radius}}, {{height}})', csharp: '' } },
  { type: 'solid-cylinder', name: 'Cylinder', icon: '⊡', inputs: [{ id: 'base', name: 'Base', type: 'point' },{ id: 'radius', name: 'Radius', type: 'number' },{ id: 'height', name: 'Height', type: 'number' }], outputs: [{ id: 'solid', name: 'Solid', type: 'mesh' }], controls: [], preview: true, codegen: { python: '{{solid}} = Geo.createCylinder({{base}}, {{radius}}, {{height}})', csharp: '' } },
  { type: 'solid-sphere', name: 'Sphere', icon: '●', inputs: [{ id: 'center', name: 'Center', type: 'point' },{ id: 'radius', name: 'Radius', type: 'number' }], outputs: [{ id: 'solid', name: 'Solid', type: 'mesh' }], controls: [], preview: true, codegen: { python: '{{solid}} = Geo.createSphere({{center}}, {{radius}})', csharp: '' } },
  { type: 'solid-torus', name: 'Torus', icon: '◎', inputs: [{ id: 'center', name: 'Center', type: 'point' },{ id: 'majorR', name: 'Major R', type: 'number' },{ id: 'minorR', name: 'Minor R', type: 'number' }], outputs: [{ id: 'solid', name: 'Solid', type: 'mesh' }], controls: [], preview: true, codegen: { python: '{{solid}} = Geo.createTorus({{center}}, {{majorR}}, {{minorR}})', csharp: '' } }
] });

// ═══════════════════════════════════════
// 15. SURFACES
// ═══════════════════════════════════════
NODE_LIBRARY.categories.push({ id: 'surfaces', name: 'Surfaces', color: '#94e2d5', icon: '◇', nodes: [
  { type: 'nurbs-surface', name: 'Surface.ByNURBS', icon: '▧', inputs: [{ id: 'grid', name: 'Ctrl Grid', type: 'list' },{ id: 'degU', name: 'Degree U', type: 'number' },{ id: 'degV', name: 'Degree V', type: 'number' }], outputs: [{ id: 'surface', name: 'Surface', type: 'mesh' }], controls: [], preview: true, codegen: { python: '{{surface}} = Geo.createNurbsSurface({{grid}}, {{degU}}, {{degV}}).toMesh()', csharp: '' } },
  { type: 'surf-from-grid', name: 'Surface.ByPointGrid', icon: '▦', inputs: [{ id: 'points', name: 'Points', type: 'list' },{ id: 'uCount', name: 'U Count', type: 'number' },{ id: 'vCount', name: 'V Count', type: 'number' }], outputs: [{ id: 'surface', name: 'Surface', type: 'mesh' }], controls: [], preview: true, codegen: { python: '{{surface}} = Geo.surfaceFromGrid({{points}}, {{uCount}}, {{vCount}})', csharp: '' } },
  { type: 'op-ruled-surface', name: 'Surface.ByRuledLoft', icon: '▨', inputs: [{ id: 'curve1', name: 'Curve 1', type: 'any' },{ id: 'curve2', name: 'Curve 2', type: 'any' }], outputs: [{ id: 'surface', name: 'Surface', type: 'mesh' }], controls: [], preview: true, codegen: { python: '{{surface}} = Geo.ruledSurface({{curve1}}, {{curve2}})', csharp: '' } },
  { type: 'op-isolines', name: 'Surface.Isolines', icon: '≡', inputs: [{ id: 'mesh', name: 'Mesh', type: 'mesh' },{ id: 'count', name: 'Count', type: 'number' }], outputs: [{ id: 'curves', name: 'Curves', type: 'list' }], controls: [{ id: 'dir', type: 'dropdown', options: ['U','V'], default: 'U', label: 'Direction' }], preview: true, codegen: { python: '{{curves}} = Geo.getIsolinesU({{mesh}}, {{count}}) if "{{ctrl.dir}}" == "U" else Geo.getIsolinesV({{mesh}}, {{count}})', csharp: '' } },
  { type: 'surf-plane', name: 'Surface.Plane', icon: '▱', inputs: [{ id: 'origin', name: 'Origin', type: 'point' },{ id: 'normal', name: 'Normal', type: 'vector' }], outputs: [{ id: 'plane', name: 'Plane', type: 'plane' }], controls: [], preview: true, codegen: { python: '{{plane}} = Geo.Plane({{origin}}, {{normal}})', csharp: '' } }
] });

// ═══════════════════════════════════════
// 16. TRANSFORM
// ═══════════════════════════════════════
NODE_LIBRARY.categories.push({ id: 'transform', name: 'Transform', color: '#f5c2e7', icon: '↗', nodes: [
  { type: 'op-array-linear', name: 'Linear Array', icon: '⋯', inputs: [{ id: 'geometry', name: 'Geometry', type: 'any' },{ id: 'direction', name: 'Direction', type: 'vector' },{ id: 'count', name: 'Count', type: 'number' },{ id: 'spacing', name: 'Spacing', type: 'number' }], outputs: [{ id: 'result', name: 'Result', type: 'list' }], controls: [], preview: true, codegen: { python: '{{result}} = Geo.arrayLinear({{geometry}}, {{direction}}, {{count}}, {{spacing}})', csharp: '' } },
  { type: 'op-mirror', name: 'Mirror', icon: '⎸', inputs: [{ id: 'geometry', name: 'Geometry', type: 'any' },{ id: 'planeOrigin', name: 'Plane Pt', type: 'point' },{ id: 'planeNormal', name: 'Plane N', type: 'vector' }], outputs: [{ id: 'result', name: 'Result', type: 'any' }], controls: [], preview: true, codegen: { python: '{{result}} = Geo.mirror({{geometry}}, {{planeOrigin}}, {{planeNormal}})', csharp: '' } },
  { type: 'op-move', name: 'Move', icon: '↗', inputs: [{ id: 'geometry', name: 'Geometry', type: 'any' },{ id: 'vector', name: 'Vector', type: 'vector' }], outputs: [{ id: 'result', name: 'Result', type: 'any' }], controls: [], preview: true, codegen: { python: '{{result}} = Geo.move({{geometry}}, {{vector}})', csharp: '' } },
  { type: 'op-array-polar', name: 'Polar Array', icon: '✱', inputs: [{ id: 'geometry', name: 'Geometry', type: 'any' },{ id: 'center', name: 'Center', type: 'point' },{ id: 'axis', name: 'Axis', type: 'vector' },{ id: 'count', name: 'Count', type: 'number' }], outputs: [{ id: 'result', name: 'Result', type: 'list' }], controls: [], preview: true, codegen: { python: '{{result}} = Geo.arrayPolar({{geometry}}, {{center}}, {{axis}}, {{count}})', csharp: '' } },
  { type: 'op-rotate', name: 'Rotate', icon: '↻', inputs: [{ id: 'geometry', name: 'Geometry', type: 'any' },{ id: 'axisOrigin', name: 'Axis Pt', type: 'point' },{ id: 'axisDir', name: 'Axis Dir', type: 'vector' },{ id: 'angle', name: 'Angle°', type: 'number' }], outputs: [{ id: 'result', name: 'Result', type: 'any' }], controls: [], preview: true, codegen: { python: '{{result}} = Geo.rotate({{geometry}}, {{axisOrigin}}, {{axisDir}}, math.radians({{angle}}))', csharp: '' } },
  { type: 'op-scale', name: 'Scale', icon: '⤡', inputs: [{ id: 'geometry', name: 'Geometry', type: 'any' },{ id: 'factor', name: 'Factor', type: 'number' },{ id: 'origin', name: 'Origin', type: 'point' }], outputs: [{ id: 'result', name: 'Result', type: 'any' }], controls: [], preview: true, codegen: { python: '{{result}} = Geo.scaleGeo({{geometry}}, {{factor}}, {{origin}})', csharp: '' } }
] });

// ═══════════════════════════════════════
// BUILD NODE_TYPE_MAP (flat lookup)
// ═══════════════════════════════════════
NODE_LIBRARY.categories.forEach(function(cat) {
  cat.nodes.forEach(function(node) {
    NODE_TYPE_MAP[node.type] = Object.assign({}, node, { categoryId: cat.id, categoryColor: cat.color });
  });
});

console.log('[NodeFlow] Node Registry — ' + NODE_LIBRARY.categories.length + ' categories, ' + Object.keys(NODE_TYPE_MAP).length + ' types');

if (typeof window !== 'undefined') {
  window.NODE_LIBRARY = NODE_LIBRARY;
  window.NODE_TYPE_MAP = NODE_TYPE_MAP;
  window.TYPE_COLORS = TYPE_COLORS;
}
